### ISSUE TITLE
card with data

### ISSUE THREAD

**Issue by roscha80** [roscha80/capstone-project#1]
# Value

As a user
I want to see a card with data from a person

# Description

![IMG_2280](https://user-images.githubusercontent.com/82395889/120758364-080bb400-c512-11eb-986d-cf3d82f6c842.jpg)

# Acceptance criteria

- [ ] A card with Name, Phone, Mail, Department and six skills should be rendered

# Task

- [ ]  feature branch
- [ ] create a list with name, number, mail and department
- [ ] create a list with six skills
- [ ]  component test

# Complexity

low

**Comment by roscha80** [comment]
# Value

As a user
I want to see a card with data 

# Description

![IMG_2280](https://user-images.githubusercontent.com/82395889/120758364-080bb400-c512-11eb-986d-cf3d82f6c842.jpg)

# Acceptance criteria

[] A card with Name, Phone, Mail, Department and six skills should be rendered

# Task

[] feature branch
[] component test

# Complexity

low
