### ISSUE TITLE
backend

### ISSUE THREAD

**Issue by roscha80** [roscha80/capstone-project#10]
# Value

As a user i want to store my data in a database 

# Description

# Acceptance criteria

- [ ] data must be stored in a database
- [ ] data must be fetched from database

# Tasks

- [ ] feature branch
- [ ] install express and mongoDB
- [ ] add routes/Crud methods
- [ ] component test

# Complexity

medium
