### ISSUE TITLE
delete user

### ISSUE THREAD

**Issue by roscha80** [roscha80/capstone-project#15]
# Value

As a user 
i want to delete single users

# Description

# Acceptance criteria

- [ ] delete single user entry

# Tasks

- [ ] feature branch
- [ ] add a delete button
- [ ] add logic to delete a single entry from the database
- [ ] component test

# Complexity

medium
