### ISSUE TITLE
list of cards

### ISSUE THREAD

**Issue by roscha80** [roscha80/capstone-project#2]
# Value

As a user 
i want to see a list of multiple cards
to see which skills my colleagues got

# Description

![IMG_2324](https://user-images.githubusercontent.com/82395889/120924653-e4449b80-c6d4-11eb-8599-cb071d020ba7.jpg)

![IMG_2280](https://user-images.githubusercontent.com/82395889/120758364-080bb400-c512-11eb-986d-cf3d82f6c842.jpg)

# Acceptance criteria

- [x] List must contain multiple cards
- [x] cards have to be numbered

# Tasks

- [x] feature branch
- [x] build component card
- [x] A card with Name, Phone, Mail, Department and six skills should be rendered
- [x] create a list with name, number, mail and department
- [x] create a list with six skills
- [x] create an array of multiple cards
- [x] component test

# Complexity

low

**Comment by roscha80** [comment]
# Value

As a user 
i want to see a list of multiple cards with data

# Description

![IMG_2282](https://user-images.githubusercontent.com/82395889/120760643-a0a33380-c514-11eb-8fd4-672a68f6395e.jpg)

# Acceptance criteria

[] List must contain multiple cards
[] cards have to be numbered
[] must contain a button called new 

# Tasks

[] feature branch
[] component test

# Complexity

low
