### ISSUE TITLE
create a new card

### ISSUE THREAD

**Issue by roscha80** [roscha80/capstone-project#3]
# Value

As a user
i want to create a new card
to got show my skills in the app

# Description

![IMG_2325](https://user-images.githubusercontent.com/82395889/120924577-b1020c80-c6d4-11eb-853a-ec7cd4a5f563.jpg)

# Acceptance criteria

- [x]  Name, phone, mail and department must be filled out
- [x] all inputfields must be labeled
- [x]  mail must be checked if it is a real mail adress
- [x]  at least one skill have to be entered
- [x]  on click back user comes to list of cards
- [x]  on save data should send to list of cards
- [x]  save the data in localstorage

# Tasks

- [x] feature branch
- [x] create a form with multiple text inputs
- [x] add a back button
- [x] add a new user button to UsersPage 
- [x] add a save/submit button
- [x] add validation for text inputs and email
- [x] add states for switching pages
- [x] save data to local storage
- [x] component test

# Complexity

medium

**Comment by roscha80** [comment]
# Value

As a user
i want to create a new card

# Description

![IMG_2281](https://user-images.githubusercontent.com/82395889/120761320-5c646300-c515-11eb-9ddc-a51866af39c6.jpg)

# Acceptance criteria

[] Name, phone, mail and department must be filled out
[] mail must be checked if it is a real mail adress
[] at least one skill have to be entered
[] on click back user comes to list of cards
[] on save data should send to list of cards

# Tasks

[] feature branch
[] component test

# Complexity

medium
