### ISSUE TITLE
filtered list with data

### ISSUE THREAD

**Issue by roscha80** [roscha80/capstone-project#4]
# Value

As a user 
i want to filter cards by skills
to show me a filtered list

# Description

![IMG_2283](https://user-images.githubusercontent.com/82395889/120777657-d00e6c00-c525-11eb-8b46-7b91fc67b8b4.jpg)

# Acceptance criteria

- [ ] filter cards by skills
- [ ] no whitespace allowed in search field
- [ ] more than one skill could be searched
- [ ] on click on single entry got to card view
- [ ] on click show all go to list with unfiltered card list

# Tasks

- [ ] feature branch
- [ ] add a input field 
- [ ] add a button show all to unfilter data
- [ ] add logic to filter a array of cards by skills
- [ ] validate input field entries
- [ ] multiple entries separated by comma
- [ ] component test

# Complexity

medium

**Comment by roscha80** [comment]
# Value

As a user 
i want to filter data by skills

# Description

![IMG_2283](https://user-images.githubusercontent.com/82395889/120777657-d00e6c00-c525-11eb-8b46-7b91fc67b8b4.jpg)

# Acceptance criteria

- [ ] filter cards by skills
- [ ] no whitespace allowed in search field
- [ ] more than one skill could be searched
- [ ] on click on single entry got to card view
- [ ] on click show all go to list with unfiltered card list

# Tasks

- [ ] feature branch
- [ ] component test

# Complexity

medium
