### ISSUE TITLE
navbar 

### ISSUE THREAD

**Issue by roscha80** [roscha80/capstone-project#8]
# Value

As a user i want navigate between my pages

# Description

![IMG_2384](https://user-images.githubusercontent.com/82395889/122066794-557e0000-cdf3-11eb-9bdb-36c74fa9a302.jpg)
![IMG_2281](https://user-images.githubusercontent.com/82395889/122066931-70e90b00-cdf3-11eb-910a-c9e2acc41414.jpg)
![IMG_2324](https://user-images.githubusercontent.com/82395889/122066969-79d9dc80-cdf3-11eb-8bc7-8201799cd3ec.jpg)

# Acceptance criteria
- [ ] switch between my pages
- [ ] change page-url

# Tasks

- [ ] feature branch
- [ ] install react-router
- [ ] add a fixed navbar at the bottom
- [ ] delete back button from createpage
- [ ] add on createpage funcitionallity to switch to listpage after submit
- [ ] add a homepage
- [ ] component test

# Complexity

medium
