### ISSUE TITLE
header

### ISSUE THREAD

**Issue by roscha80** [roscha80/capstone-project#9]
#Value

As a user 
i want to see on which page i'm 
when i click on the navbar

# Description

![IMG_2385](https://user-images.githubusercontent.com/82395889/122067375-d2a97500-cdf3-11eb-81de-9a2c42b28318.jpg)
![IMG_2324](https://user-images.githubusercontent.com/82395889/122067380-d3420b80-cdf3-11eb-9714-bb94bd383892.jpg)
![IMG_2281](https://user-images.githubusercontent.com/82395889/122067383-d3daa200-cdf3-11eb-9b63-969244d54d24.jpg)

# Acceptance criteria

- [x] text must be switch dynamic if i change the site
- [ ] must be a h2
- [x] header must be show every time

# Tasks

- [x] feature branch
- [x] add component
- [x] must be show in the app component
- [x] change text on navbar click
- [x] component test

# Complexity

low
